name: fresh_sessions_secure_storage
description: Secure sessions storage for fresh_sessions built on top of flutter_secure_storage.
repository: https://github.com/felangel/fresh
issue_tracker: https://github.com/felangel/fresh/issues
homepage: https://github.com/felangel/fresh

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  fresh_sessions:
    path: ../fresh_sessions

dev_dependencies:
  flutter_test:
    sdk: flutter
